from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .equipoCreateView import EquipoCreateView
from .convocatoriaView import ConvocatoriaCreateView
from .convocatoriaView import ConvocatoriaDetailView
from .convocatoriaView import ConvocatoriaListView
from .convocatoriaView import ConvocatoriaUpdateView
from .convocatoriaView import ConvocatoriaDeleteView
from .jugadorView import JugadorCreateView
